/*
	XML2SCD
	Convert XML data to .h and .c files to process SCD stuff

	Copyright (C) 2014	Patrice Mandin

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include <stdio.h>
#include <string.h>

#include <libxml/xmlversion.h>
#include <libxml/xmlreader.h>
#include <libxml/xpath.h>

/*--- Functions prototypes ---*/

void generateDefines(xmlDocPtr doc);
void generateTypes(xmlDocPtr doc);
void generateTypeFields(xmlNodePtr node);

xmlXPathObjectPtr xpathSearch (xmlDocPtr doc, xmlChar *xpath);

/*--- Functions ---*/

int main(int argc, char **argv)
{
	xmlDocPtr doc;

	if (argc<3) {
		fprintf(stderr, "Usage: %s /path/to/scdN.xml [--defines|--types]\n", argv[0]);
		return 1;
	}

	LIBXML_TEST_VERSION
	xmlInitParser();

	doc = xmlParseFile(argv[1]);
	if (doc) {
		if (strcmp(argv[2],"--defines")==0) {
			generateDefines(doc);
		}
		if (strcmp(argv[2],"--types")==0) {
			generateTypes(doc);
		}
	} else {
		fprintf(stderr, "xml2scd: Can not read %s\n", argv[1]);
	}

	xmlCleanupParser();
	xmlMemoryDump();

	return 0;
}

void generateDefines(xmlDocPtr doc)
{
	xmlXPathObjectPtr path;
	xmlChar *inst_name, *inst_id;
	char *inst_name_up;
	xmlNodeSetPtr nodeset;
	int i, j;

	path = (xmlXPathObjectPtr) xpathSearch(doc, "/scd/*[name()]");
	if (!path) {
		fprintf(stderr, "xml2scd: Path not found\n");
	}

	printf("/* Generated by xml2scd */\n");

	nodeset = path->nodesetval;
	for (i=0; i < nodeset->nodeNr; i++) {
		xmlNodePtr node;
				
		node = nodeset->nodeTab[i];
		if (strcmp(node->name, "inst")!=0) {
			continue;
		}

		inst_name = xmlGetProp(node, "name");
		inst_id = xmlGetProp(node, "id");

		/* Convert to upper case for define */
		inst_name_up = strdup(inst_name);
		j=0;
		while (inst_name_up[j]) {
			inst_name_up[j] = toupper(inst_name_up[j]);
			++j;
		}

		printf("#define INST_%s\t%s\n", inst_name_up, inst_id);

		free(inst_name_up);
	}

	xmlXPathFreeObject(path);
}

void generateTypes(xmlDocPtr doc)
{
	xmlXPathObjectPtr path;
	xmlChar *inst_name, *inst_id;
	char *inst_name_low;
	xmlNodeSetPtr nodeset;
	int i, j;

	path = (xmlXPathObjectPtr) xpathSearch(doc, "/scd/*[name()]");
	if (!path) {
		fprintf(stderr, "xml2scd: Path not found\n");
	}

	printf("/* Generated by xml2scd */\n");

	nodeset = path->nodesetval;
	for (i=0; i < nodeset->nodeNr; i++) {
		xmlNodePtr node;
				
		node = nodeset->nodeTab[i];
		if (strcmp(node->name, "inst")!=0) {
			continue;
		}

		inst_name = xmlGetProp(node, "name");

		/* Convert to upper case for define */
		inst_name_low = strdup(inst_name);
		j=0;
		while (inst_name_low[j]) {
			inst_name_low[j] = tolower(inst_name_low[j]);
			++j;
		}

		printf("\n" "typedef struct {\n");
		generateTypeFields(node);		
		printf("} inst_%s_t;\n", inst_name_low);

		free(inst_name_low);
	}

	xmlXPathFreeObject(path);
}

void generateTypeFields(xmlNodePtr node)
{
	xmlNodePtr child;
	xmlChar *field_name, *field_type;

	for (child = node->children; child; child = child->next) {
		if (child->type != XML_ELEMENT_NODE) {
			continue;
		}

		field_name = xmlGetProp(child, "name");
		field_type = xmlGetProp(child, "type");

		printf("\t%s\t%s;\n", field_type, field_name);
	}
}

xmlXPathObjectPtr xpathSearch (xmlDocPtr doc, xmlChar *xpath)
{
	xmlXPathContextPtr context;
	xmlXPathObjectPtr result;

	context = xmlXPathNewContext(doc);
	result = xmlXPathEvalExpression(xpath, context);
	if(xmlXPathNodeSetIsEmpty(result->nodesetval))
	{
		return NULL;
	}
	xmlXPathFreeContext(context);

	return result;
}
